// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: internal/proto/ci.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Copy_Direction int32

const (
	Copy_TO_WORKER   Copy_Direction = 0 // server -> worker (data sent inline)
	Copy_FROM_WORKER Copy_Direction = 1 // worker -> server (data sent as FileChunks)
)

// Enum value maps for Copy_Direction.
var (
	Copy_Direction_name = map[int32]string{
		0: "TO_WORKER",
		1: "FROM_WORKER",
	}
	Copy_Direction_value = map[string]int32{
		"TO_WORKER":   0,
		"FROM_WORKER": 1,
	}
)

func (x Copy_Direction) Enum() *Copy_Direction {
	p := new(Copy_Direction)
	*p = x
	return p
}

func (x Copy_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Copy_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_ci_proto_enumTypes[0].Descriptor()
}

func (Copy_Direction) Type() protoreflect.EnumType {
	return &file_internal_proto_ci_proto_enumTypes[0]
}

func (x Copy_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Copy_Direction.Descriptor instead.
func (Copy_Direction) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{5, 0}
}

type Output_Stream int32

const (
	Output_STDOUT Output_Stream = 0
	Output_STDERR Output_Stream = 1
)

// Enum value maps for Output_Stream.
var (
	Output_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	Output_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x Output_Stream) Enum() *Output_Stream {
	p := new(Output_Stream)
	*p = x
	return p
}

func (x Output_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Output_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_ci_proto_enumTypes[1].Descriptor()
}

func (Output_Stream) Type() protoreflect.EnumType {
	return &file_internal_proto_ci_proto_enumTypes[1]
}

func (x Output_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Output_Stream.Descriptor instead.
func (Output_Stream) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{9, 0}
}

// Messages from worker to server
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // references server command (0 = no associated command)
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_RunnerInfo
	//	*WorkerMessage_Output
	//	*WorkerMessage_Done
	//	*WorkerMessage_FileChunk
	//	*WorkerMessage_Error
	//	*WorkerMessage_ContextRequest
	//	*WorkerMessage_SaveArtifact
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_internal_proto_ci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRunnerInfo() *RunnerInfo {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_RunnerInfo); ok {
			return x.RunnerInfo
		}
	}
	return nil
}

func (x *WorkerMessage) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *WorkerMessage) GetDone() *Done {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *WorkerMessage) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *WorkerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WorkerMessage) GetContextRequest() *ContextRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ContextRequest); ok {
			return x.ContextRequest
		}
	}
	return nil
}

func (x *WorkerMessage) GetSaveArtifact() *SaveArtifact {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_SaveArtifact); ok {
			return x.SaveArtifact
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_RunnerInfo struct {
	RunnerInfo *RunnerInfo `protobuf:"bytes,2,opt,name=runner_info,json=runnerInfo,proto3,oneof"` // sent once on connect
}

type WorkerMessage_Output struct {
	Output *Output `protobuf:"bytes,3,opt,name=output,proto3,oneof"` // stdout/stderr of running command
}

type WorkerMessage_Done struct {
	Done *Done `protobuf:"bytes,4,opt,name=done,proto3,oneof"` // command finished
}

type WorkerMessage_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,5,opt,name=file_chunk,json=fileChunk,proto3,oneof"` // file chunk being sent
}

type WorkerMessage_Error struct {
	Error *Error `protobuf:"bytes,6,opt,name=error,proto3,oneof"` // command error
}

type WorkerMessage_ContextRequest struct {
	ContextRequest *ContextRequest `protobuf:"bytes,7,opt,name=context_request,json=contextRequest,proto3,oneof"` // request for context
}

type WorkerMessage_SaveArtifact struct {
	SaveArtifact *SaveArtifact `protobuf:"bytes,8,opt,name=save_artifact,json=saveArtifact,proto3,oneof"` // save artifact (e.g. sarif report)
}

func (*WorkerMessage_RunnerInfo) isWorkerMessage_Payload() {}

func (*WorkerMessage_Output) isWorkerMessage_Payload() {}

func (*WorkerMessage_Done) isWorkerMessage_Payload() {}

func (*WorkerMessage_FileChunk) isWorkerMessage_Payload() {}

func (*WorkerMessage_Error) isWorkerMessage_Payload() {}

func (*WorkerMessage_ContextRequest) isWorkerMessage_Payload() {}

func (*WorkerMessage_SaveArtifact) isWorkerMessage_Payload() {}

// Messages from server to worker
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // sequential command id
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Copy
	//	*ServerMessage_Run
	//	*ServerMessage_Close
	//	*ServerMessage_ContextResponse
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_proto_ci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetCopy() *Copy {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Copy); ok {
			return x.Copy
		}
	}
	return nil
}

func (x *ServerMessage) GetRun() *Run {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Run); ok {
			return x.Run
		}
	}
	return nil
}

func (x *ServerMessage) GetClose() *Close {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ServerMessage) GetContextResponse() *ContextResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ContextResponse); ok {
			return x.ContextResponse
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Copy struct {
	Copy *Copy `protobuf:"bytes,2,opt,name=copy,proto3,oneof"`
}

type ServerMessage_Run struct {
	Run *Run `protobuf:"bytes,3,opt,name=run,proto3,oneof"`
}

type ServerMessage_Close struct {
	Close *Close `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type ServerMessage_ContextResponse struct {
	ContextResponse *ContextResponse `protobuf:"bytes,5,opt,name=context_response,json=contextResponse,proto3,oneof"` // context response
}

func (*ServerMessage_Copy) isServerMessage_Payload() {}

func (*ServerMessage_Run) isServerMessage_Payload() {}

func (*ServerMessage_Close) isServerMessage_Payload() {}

func (*ServerMessage_ContextResponse) isServerMessage_Payload() {}

// Context request
type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_internal_proto_ci_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{2}
}

// Context response
type ContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_internal_proto_ci_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{3}
}

func (x *ContextResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContextResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Runner info, sent on connect
type RunnerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerInfo) Reset() {
	*x = RunnerInfo{}
	mi := &file_internal_proto_ci_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerInfo) ProtoMessage() {}

func (x *RunnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerInfo.ProtoReflect.Descriptor instead.
func (*RunnerInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{4}
}

func (x *RunnerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RunnerInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RunnerInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RunnerInfo) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *RunnerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Copy files - bidirectional
type Copy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     Copy_Direction         `protobuf:"varint,1,opt,name=direction,proto3,enum=ci.Copy_Direction" json:"direction,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // source path (for FROM_WORKER) or filename (for TO_WORKER)
	Dest          string                 `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`     // destination path
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`     // file data (for TO_WORKER, small files)
	Creds         *Credentials           `protobuf:"bytes,5,opt,name=creds,proto3" json:"creds,omitempty"`   // optional (deprecated, use Run with git)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Copy) Reset() {
	*x = Copy{}
	mi := &file_internal_proto_ci_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Copy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Copy) ProtoMessage() {}

func (x *Copy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Copy.ProtoReflect.Descriptor instead.
func (*Copy) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{5}
}

func (x *Copy) GetDirection() Copy_Direction {
	if x != nil {
		return x.Direction
	}
	return Copy_TO_WORKER
}

func (x *Copy) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Copy) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Copy) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Copy) GetCreds() *Credentials {
	if x != nil {
		return x.Creds
	}
	return nil
}

type Credentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Auth:
	//
	//	*Credentials_Token
	//	*Credentials_Basic
	Auth          isCredentials_Auth `protobuf_oneof:"auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_internal_proto_ci_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{6}
}

func (x *Credentials) GetAuth() isCredentials_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Credentials) GetToken() string {
	if x != nil {
		if x, ok := x.Auth.(*Credentials_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *Credentials) GetBasic() *BasicAuth {
	if x != nil {
		if x, ok := x.Auth.(*Credentials_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

type isCredentials_Auth interface {
	isCredentials_Auth()
}

type Credentials_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type Credentials_Basic struct {
	Basic *BasicAuth `protobuf:"bytes,2,opt,name=basic,proto3,oneof"`
}

func (*Credentials_Token) isCredentials_Auth() {}

func (*Credentials_Basic) isCredentials_Auth() {}

type BasicAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	mi := &file_internal_proto_ci_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{7}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Execute command
type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir       string                 `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_internal_proto_ci_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{8}
}

func (x *Run) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Run) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Run) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Run) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

// Output stream
type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        Output_Stream          `protobuf:"varint,1,opt,name=stream,proto3,enum=ci.Output_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_internal_proto_ci_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{9}
}

func (x *Output) GetStream() Output_Stream {
	if x != nil {
		return x.Stream
	}
	return Output_STDOUT
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Command finished
type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_internal_proto_ci_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{10}
}

func (x *Done) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// File chunk (for large transfers)
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_internal_proto_ci_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{11}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// Error
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_proto_ci_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{12}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Close connection
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_internal_proto_ci_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{13}
}

// Save artifact (simple one-shot upload for reports)
type SaveArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArtifact) Reset() {
	*x = SaveArtifact{}
	mi := &file_internal_proto_ci_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArtifact) ProtoMessage() {}

func (x *SaveArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ci_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArtifact.ProtoReflect.Descriptor instead.
func (*SaveArtifact) Descriptor() ([]byte, []int) {
	return file_internal_proto_ci_proto_rawDescGZIP(), []int{14}
}

func (x *SaveArtifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveArtifact) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_proto_ci_proto protoreflect.FileDescriptor

const file_internal_proto_ci_proto_rawDesc = "" +
	"\n" +
	"\x17internal/proto/ci.proto\x12\x02ci\"\xee\x02\n" +
	"\rWorkerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x121\n" +
	"\vrunner_info\x18\x02 \x01(\v2\x0e.ci.RunnerInfoH\x00R\n" +
	"runnerInfo\x12$\n" +
	"\x06output\x18\x03 \x01(\v2\n" +
	".ci.OutputH\x00R\x06output\x12\x1e\n" +
	"\x04done\x18\x04 \x01(\v2\b.ci.DoneH\x00R\x04done\x12.\n" +
	"\n" +
	"file_chunk\x18\x05 \x01(\v2\r.ci.FileChunkH\x00R\tfileChunk\x12!\n" +
	"\x05error\x18\x06 \x01(\v2\t.ci.ErrorH\x00R\x05error\x12=\n" +
	"\x0fcontext_request\x18\a \x01(\v2\x12.ci.ContextRequestH\x00R\x0econtextRequest\x127\n" +
	"\rsave_artifact\x18\b \x01(\v2\x10.ci.SaveArtifactH\x00R\fsaveArtifactB\t\n" +
	"\apayload\"\xcc\x01\n" +
	"\rServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1e\n" +
	"\x04copy\x18\x02 \x01(\v2\b.ci.CopyH\x00R\x04copy\x12\x1b\n" +
	"\x03run\x18\x03 \x01(\v2\a.ci.RunH\x00R\x03run\x12!\n" +
	"\x05close\x18\x04 \x01(\v2\t.ci.CloseH\x00R\x05close\x12@\n" +
	"\x10context_response\x18\x05 \x01(\v2\x13.ci.ContextResponseH\x00R\x0fcontextResponseB\t\n" +
	"\apayload\"\x10\n" +
	"\x0eContextRequest\"\x8f\x01\n" +
	"\x0fContextResponse\x12.\n" +
	"\x03env\x18\x01 \x03(\v2\x1c.ci.ContextResponse.EnvEntryR\x03env\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\n" +
	"RunnerInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12/\n" +
	"\x05extra\x18\x04 \x03(\v2\x19.ci.RunnerInfo.ExtraEntryR\x05extra\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x04Copy\x120\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x12.ci.Copy.DirectionR\tdirection\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\tR\x04dest\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12%\n" +
	"\x05creds\x18\x05 \x01(\v2\x0f.ci.CredentialsR\x05creds\"+\n" +
	"\tDirection\x12\r\n" +
	"\tTO_WORKER\x10\x00\x12\x0f\n" +
	"\vFROM_WORKER\x10\x01\"T\n" +
	"\vCredentials\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12%\n" +
	"\x05basic\x18\x02 \x01(\v2\r.ci.BasicAuthH\x00R\x05basicB\x06\n" +
	"\x04auth\"C\n" +
	"\tBasicAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa1\x01\n" +
	"\x03Run\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\"\n" +
	"\x03env\x18\x03 \x03(\v2\x10.ci.Run.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x06Output\x12)\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x11.ci.Output.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"#\n" +
	"\x04Done\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"1\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Close\"6\n" +
	"\fSaveArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2=\n" +
	"\x06Server\x123\n" +
	"\aConnect\x12\x11.ci.WorkerMessage\x1a\x11.ci.ServerMessage(\x010\x01B\x10Z\x0einternal/protob\x06proto3"

var (
	file_internal_proto_ci_proto_rawDescOnce sync.Once
	file_internal_proto_ci_proto_rawDescData []byte
)

func file_internal_proto_ci_proto_rawDescGZIP() []byte {
	file_internal_proto_ci_proto_rawDescOnce.Do(func() {
		file_internal_proto_ci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_ci_proto_rawDesc), len(file_internal_proto_ci_proto_rawDesc)))
	})
	return file_internal_proto_ci_proto_rawDescData
}

var file_internal_proto_ci_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_ci_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_proto_ci_proto_goTypes = []any{
	(Copy_Direction)(0),     // 0: ci.Copy.Direction
	(Output_Stream)(0),      // 1: ci.Output.Stream
	(*WorkerMessage)(nil),   // 2: ci.WorkerMessage
	(*ServerMessage)(nil),   // 3: ci.ServerMessage
	(*ContextRequest)(nil),  // 4: ci.ContextRequest
	(*ContextResponse)(nil), // 5: ci.ContextResponse
	(*RunnerInfo)(nil),      // 6: ci.RunnerInfo
	(*Copy)(nil),            // 7: ci.Copy
	(*Credentials)(nil),     // 8: ci.Credentials
	(*BasicAuth)(nil),       // 9: ci.BasicAuth
	(*Run)(nil),             // 10: ci.Run
	(*Output)(nil),          // 11: ci.Output
	(*Done)(nil),            // 12: ci.Done
	(*FileChunk)(nil),       // 13: ci.FileChunk
	(*Error)(nil),           // 14: ci.Error
	(*Close)(nil),           // 15: ci.Close
	(*SaveArtifact)(nil),    // 16: ci.SaveArtifact
	nil,                     // 17: ci.ContextResponse.EnvEntry
	nil,                     // 18: ci.RunnerInfo.ExtraEntry
	nil,                     // 19: ci.Run.EnvEntry
}
var file_internal_proto_ci_proto_depIdxs = []int32{
	6,  // 0: ci.WorkerMessage.runner_info:type_name -> ci.RunnerInfo
	11, // 1: ci.WorkerMessage.output:type_name -> ci.Output
	12, // 2: ci.WorkerMessage.done:type_name -> ci.Done
	13, // 3: ci.WorkerMessage.file_chunk:type_name -> ci.FileChunk
	14, // 4: ci.WorkerMessage.error:type_name -> ci.Error
	4,  // 5: ci.WorkerMessage.context_request:type_name -> ci.ContextRequest
	16, // 6: ci.WorkerMessage.save_artifact:type_name -> ci.SaveArtifact
	7,  // 7: ci.ServerMessage.copy:type_name -> ci.Copy
	10, // 8: ci.ServerMessage.run:type_name -> ci.Run
	15, // 9: ci.ServerMessage.close:type_name -> ci.Close
	5,  // 10: ci.ServerMessage.context_response:type_name -> ci.ContextResponse
	17, // 11: ci.ContextResponse.env:type_name -> ci.ContextResponse.EnvEntry
	18, // 12: ci.RunnerInfo.extra:type_name -> ci.RunnerInfo.ExtraEntry
	0,  // 13: ci.Copy.direction:type_name -> ci.Copy.Direction
	8,  // 14: ci.Copy.creds:type_name -> ci.Credentials
	9,  // 15: ci.Credentials.basic:type_name -> ci.BasicAuth
	19, // 16: ci.Run.env:type_name -> ci.Run.EnvEntry
	1,  // 17: ci.Output.stream:type_name -> ci.Output.Stream
	2,  // 18: ci.Server.Connect:input_type -> ci.WorkerMessage
	3,  // 19: ci.Server.Connect:output_type -> ci.ServerMessage
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_proto_ci_proto_init() }
func file_internal_proto_ci_proto_init() {
	if File_internal_proto_ci_proto != nil {
		return
	}
	file_internal_proto_ci_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_RunnerInfo)(nil),
		(*WorkerMessage_Output)(nil),
		(*WorkerMessage_Done)(nil),
		(*WorkerMessage_FileChunk)(nil),
		(*WorkerMessage_Error)(nil),
		(*WorkerMessage_ContextRequest)(nil),
		(*WorkerMessage_SaveArtifact)(nil),
	}
	file_internal_proto_ci_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Copy)(nil),
		(*ServerMessage_Run)(nil),
		(*ServerMessage_Close)(nil),
		(*ServerMessage_ContextResponse)(nil),
	}
	file_internal_proto_ci_proto_msgTypes[6].OneofWrappers = []any{
		(*Credentials_Token)(nil),
		(*Credentials_Basic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_ci_proto_rawDesc), len(file_internal_proto_ci_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_ci_proto_goTypes,
		DependencyIndexes: file_internal_proto_ci_proto_depIdxs,
		EnumInfos:         file_internal_proto_ci_proto_enumTypes,
		MessageInfos:      file_internal_proto_ci_proto_msgTypes,
	}.Build()
	File_internal_proto_ci_proto = out.File
	file_internal_proto_ci_proto_goTypes = nil
	file_internal_proto_ci_proto_depIdxs = nil
}
