// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/ci.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Matriz_Connect_FullMethodName = "/ci.Matriz/Connect"
)

// MatrizClient is the client API for Matriz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker conecta na matriz e abre stream bidirecional
type MatrizClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, MatrizMessage], error)
}

type matrizClient struct {
	cc grpc.ClientConnInterface
}

func NewMatrizClient(cc grpc.ClientConnInterface) MatrizClient {
	return &matrizClient{cc}
}

func (c *matrizClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, MatrizMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Matriz_ServiceDesc.Streams[0], Matriz_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, MatrizMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Matriz_ConnectClient = grpc.BidiStreamingClient[WorkerMessage, MatrizMessage]

// MatrizServer is the server API for Matriz service.
// All implementations must embed UnimplementedMatrizServer
// for forward compatibility.
//
// Worker conecta na matriz e abre stream bidirecional
type MatrizServer interface {
	Connect(grpc.BidiStreamingServer[WorkerMessage, MatrizMessage]) error
	mustEmbedUnimplementedMatrizServer()
}

// UnimplementedMatrizServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatrizServer struct{}

func (UnimplementedMatrizServer) Connect(grpc.BidiStreamingServer[WorkerMessage, MatrizMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMatrizServer) mustEmbedUnimplementedMatrizServer() {}
func (UnimplementedMatrizServer) testEmbeddedByValue()                {}

// UnsafeMatrizServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatrizServer will
// result in compilation errors.
type UnsafeMatrizServer interface {
	mustEmbedUnimplementedMatrizServer()
}

func RegisterMatrizServer(s grpc.ServiceRegistrar, srv MatrizServer) {
	// If the following call panics, it indicates UnimplementedMatrizServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Matriz_ServiceDesc, srv)
}

func _Matriz_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatrizServer).Connect(&grpc.GenericServerStream[WorkerMessage, MatrizMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Matriz_ConnectServer = grpc.BidiStreamingServer[WorkerMessage, MatrizMessage]

// Matriz_ServiceDesc is the grpc.ServiceDesc for Matriz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Matriz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ci.Matriz",
	HandlerType: (*MatrizServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Matriz_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ci.proto",
}
