// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const appendLog = `-- name: AppendLog :exec
INSERT INTO log_entries (run_id, timestamp, stream, data)
VALUES (?, ?, ?, ?)
`

type AppendLogParams struct {
	RunID     string    `json:"run_id"`
	Timestamp time.Time `json:"timestamp"`
	Stream    string    `json:"stream"`
	Data      string    `json:"data"`
}

func (q *Queries) AppendLog(ctx context.Context, arg AppendLogParams) error {
	_, err := q.db.ExecContext(ctx, appendLog,
		arg.RunID,
		arg.Timestamp,
		arg.Stream,
		arg.Data,
	)
	return err
}

const checkRepoExists = `-- name: CheckRepoExists :one
SELECT 1 FROM repos WHERE clone_url = ? LIMIT 1
`

func (q *Queries) CheckRepoExists(ctx context.Context, cloneUrl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkRepoExists, cloneUrl)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRepo = `-- name: CreateRepo :exec
INSERT INTO repos (clone_url)
VALUES (?)
`

func (q *Queries) CreateRepo(ctx context.Context, cloneUrl string) error {
	_, err := q.db.ExecContext(ctx, createRepo, cloneUrl)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, status, started_at, finished_at, exit_code, ui_token, git_link, repo_url, commit_message, author, branch)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRunParams struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt64  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	GitLink       string         `json:"git_link"`
	RepoUrl       sql.NullString `json:"repo_url"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ExitCode,
		arg.UiToken,
		arg.GitLink,
		arg.RepoUrl,
		arg.CommitMessage,
		arg.Author,
		arg.Branch,
	)
	return err
}

const createSarifIssue = `-- name: CreateSarifIssue :exec
INSERT INTO sarif_issues (sarif_run_id, rule_id, message, path, line, severity)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSarifIssueParams struct {
	SarifRunID string         `json:"sarif_run_id"`
	RuleID     string         `json:"rule_id"`
	Message    string         `json:"message"`
	Path       string         `json:"path"`
	Line       sql.NullInt64  `json:"line"`
	Severity   sql.NullString `json:"severity"`
}

func (q *Queries) CreateSarifIssue(ctx context.Context, arg CreateSarifIssueParams) error {
	_, err := q.db.ExecContext(ctx, createSarifIssue,
		arg.SarifRunID,
		arg.RuleID,
		arg.Message,
		arg.Path,
		arg.Line,
		arg.Severity,
	)
	return err
}

const createSarifRun = `-- name: CreateSarifRun :exec
INSERT INTO sarif_runs (id, run_id, tool)
VALUES (?, ?, ?)
`

type CreateSarifRunParams struct {
	ID    string `json:"id"`
	RunID string `json:"run_id"`
	Tool  string `json:"tool"`
}

func (q *Queries) CreateSarifRun(ctx context.Context, arg CreateSarifRunParams) error {
	_, err := q.db.ExecContext(ctx, createSarifRun, arg.ID, arg.RunID, arg.Tool)
	return err
}

const getLogs = `-- name: GetLogs :many
SELECT timestamp, stream, data
FROM log_entries
WHERE run_id = ?
ORDER BY id ASC
`

type GetLogsRow struct {
	Timestamp time.Time `json:"timestamp"`
	Stream    string    `json:"stream"`
	Data      string    `json:"data"`
}

func (q *Queries) GetLogs(ctx context.Context, runID string) ([]GetLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLogsRow{}
	for rows.Next() {
		var i GetLogsRow
		if err := rows.Scan(&i.Timestamp, &i.Stream, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepo = `-- name: GetRepo :one
SELECT clone_url
FROM repos
WHERE clone_url = ?
`

func (q *Queries) GetRepo(ctx context.Context, cloneUrl string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRepo, cloneUrl)
	var clone_url string
	err := row.Scan(&clone_url)
	return clone_url, err
}

const getRun = `-- name: GetRun :one
SELECT id, status, started_at, finished_at, exit_code, ui_token, git_link, repo_url, commit_message, author, branch
FROM runs
WHERE id = ?
`

type GetRunRow struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt64  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	GitLink       string         `json:"git_link"`
	RepoUrl       sql.NullString `json:"repo_url"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.UiToken,
		&i.GitLink,
		&i.RepoUrl,
		&i.CommitMessage,
		&i.Author,
		&i.Branch,
	)
	return i, err
}

const getRunsWithoutRepoURL = `-- name: GetRunsWithoutRepoURL :many
SELECT id, status, started_at, finished_at, exit_code, ui_token, git_link, repo_url, commit_message, author, branch
FROM runs
WHERE repo_url IS NULL OR repo_url = ''
LIMIT ?
`

type GetRunsWithoutRepoURLRow struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt64  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	GitLink       string         `json:"git_link"`
	RepoUrl       sql.NullString `json:"repo_url"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
}

func (q *Queries) GetRunsWithoutRepoURL(ctx context.Context, limit int64) ([]GetRunsWithoutRepoURLRow, error) {
	rows, err := q.db.QueryContext(ctx, getRunsWithoutRepoURL, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRunsWithoutRepoURLRow{}
	for rows.Next() {
		var i GetRunsWithoutRepoURLRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.UiToken,
			&i.GitLink,
			&i.RepoUrl,
			&i.CommitMessage,
			&i.Author,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStuckRuns = `-- name: GetStuckRuns :many
SELECT id, status, started_at, finished_at, exit_code, ui_token, git_link, repo_url, commit_message, author, branch
FROM runs
WHERE status IN ('scheduled', 'running')
AND started_at < ?
LIMIT ?
`

type GetStuckRunsParams struct {
	StartedAt time.Time `json:"started_at"`
	Limit     int64     `json:"limit"`
}

type GetStuckRunsRow struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt64  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	GitLink       string         `json:"git_link"`
	RepoUrl       sql.NullString `json:"repo_url"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
}

func (q *Queries) GetStuckRuns(ctx context.Context, arg GetStuckRunsParams) ([]GetStuckRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStuckRuns, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStuckRunsRow{}
	for rows.Next() {
		var i GetStuckRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.UiToken,
			&i.GitLink,
			&i.RepoUrl,
			&i.CommitMessage,
			&i.Author,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT DISTINCT repo_url
FROM runs
WHERE repo_url IS NOT NULL AND repo_url != ''
ORDER BY repo_url
`

func (q *Queries) ListRepos(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var repo_url sql.NullString
		if err := rows.Scan(&repo_url); err != nil {
			return nil, err
		}
		items = append(items, repo_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, status, started_at, finished_at, exit_code, ui_token, git_link, repo_url, commit_message, author, branch
FROM runs
WHERE (?1 IS NULL OR repo_url = ?1)
ORDER BY started_at DESC
LIMIT ?3 OFFSET ?2
`

type ListRunsParams struct {
	RepoUrl interface{} `json:"repo_url"`
	Offset  int64       `json:"offset"`
	Limit   int64       `json:"limit"`
}

type ListRunsRow struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt64  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	GitLink       string         `json:"git_link"`
	RepoUrl       sql.NullString `json:"repo_url"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, arg.RepoUrl, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.UiToken,
			&i.GitLink,
			&i.RepoUrl,
			&i.CommitMessage,
			&i.Author,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSarifIssuesForRepo = `-- name: ListSarifIssuesForRepo :many
SELECT i.rule_id, i.message, i.path, i.line, i.severity, r.tool, runs.id as run_id, runs.commit_message
FROM sarif_issues i
JOIN sarif_runs r ON i.sarif_run_id = r.id
JOIN runs ON r.run_id = runs.id
WHERE runs.repo_url = ?
ORDER BY runs.created_at DESC
LIMIT ?
`

type ListSarifIssuesForRepoParams struct {
	RepoUrl sql.NullString `json:"repo_url"`
	Limit   int64          `json:"limit"`
}

type ListSarifIssuesForRepoRow struct {
	RuleID        string         `json:"rule_id"`
	Message       string         `json:"message"`
	Path          string         `json:"path"`
	Line          sql.NullInt64  `json:"line"`
	Severity      sql.NullString `json:"severity"`
	Tool          string         `json:"tool"`
	RunID         string         `json:"run_id"`
	CommitMessage string         `json:"commit_message"`
}

func (q *Queries) ListSarifIssuesForRepo(ctx context.Context, arg ListSarifIssuesForRepoParams) ([]ListSarifIssuesForRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listSarifIssuesForRepo, arg.RepoUrl, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSarifIssuesForRepoRow{}
	for rows.Next() {
		var i ListSarifIssuesForRepoRow
		if err := rows.Scan(
			&i.RuleID,
			&i.Message,
			&i.Path,
			&i.Line,
			&i.Severity,
			&i.Tool,
			&i.RunID,
			&i.CommitMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSarifIssuesForRun = `-- name: ListSarifIssuesForRun :many
SELECT i.rule_id, i.message, i.path, i.line, i.severity, r.tool
FROM sarif_issues i
JOIN sarif_runs r ON i.sarif_run_id = r.id
WHERE r.run_id = ?
`

type ListSarifIssuesForRunRow struct {
	RuleID   string         `json:"rule_id"`
	Message  string         `json:"message"`
	Path     string         `json:"path"`
	Line     sql.NullInt64  `json:"line"`
	Severity sql.NullString `json:"severity"`
	Tool     string         `json:"tool"`
}

func (q *Queries) ListSarifIssuesForRun(ctx context.Context, runID string) ([]ListSarifIssuesForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listSarifIssuesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSarifIssuesForRunRow{}
	for rows.Next() {
		var i ListSarifIssuesForRunRow
		if err := rows.Scan(
			&i.RuleID,
			&i.Message,
			&i.Path,
			&i.Line,
			&i.Severity,
			&i.Tool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunRepoURL = `-- name: UpdateRunRepoURL :exec
UPDATE runs
SET repo_url = ?
WHERE id = ?
`

type UpdateRunRepoURLParams struct {
	RepoUrl sql.NullString `json:"repo_url"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateRunRepoURL(ctx context.Context, arg UpdateRunRepoURLParams) error {
	_, err := q.db.ExecContext(ctx, updateRunRepoURL, arg.RepoUrl, arg.ID)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs
SET status = ?, exit_code = ?, finished_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRunStatusParams struct {
	Status     string        `json:"status"`
	ExitCode   sql.NullInt64 `json:"exit_code"`
	FinishedAt sql.NullTime  `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus,
		arg.Status,
		arg.ExitCode,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
