// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	CreateWorkerToken(ctx context.Context, arg CreateWorkerTokenParams) error
	DeleteWorkerToken(ctx context.Context, id string) error
	GetWorkerToken(ctx context.Context, id string) (WorkerToken, error)
	ListWorkerTokens(ctx context.Context) ([]WorkerToken, error)
	RevokeWorkerToken(ctx context.Context, arg RevokeWorkerTokenParams) error
}

var _ Querier = (*Queries)(nil)
