// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const createWorkerToken = `-- name: CreateWorkerToken :exec
INSERT INTO worker_tokens (id, name, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateWorkerTokenParams struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) CreateWorkerToken(ctx context.Context, arg CreateWorkerTokenParams) error {
	_, err := q.db.ExecContext(ctx, createWorkerToken,
		arg.ID,
		arg.Name,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkerToken = `-- name: DeleteWorkerToken :exec
DELETE FROM worker_tokens
WHERE id = ?
`

func (q *Queries) DeleteWorkerToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkerToken, id)
	return err
}

const getWorkerToken = `-- name: GetWorkerToken :one
SELECT id, name, expires_at, revoked_at, created_at, updated_at
FROM worker_tokens
WHERE id = ?
`

func (q *Queries) GetWorkerToken(ctx context.Context, id string) (WorkerToken, error) {
	row := q.db.QueryRowContext(ctx, getWorkerToken, id)
	var i WorkerToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkerTokens = `-- name: ListWorkerTokens :many
SELECT id, name, expires_at, revoked_at, created_at, updated_at
FROM worker_tokens
ORDER BY created_at DESC
`

func (q *Queries) ListWorkerTokens(ctx context.Context) ([]WorkerToken, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerToken{}
	for rows.Next() {
		var i WorkerToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkerToken = `-- name: RevokeWorkerToken :exec
UPDATE worker_tokens
SET revoked_at = ?, updated_at = ?
WHERE id = ?
`

type RevokeWorkerTokenParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) RevokeWorkerToken(ctx context.Context, arg RevokeWorkerTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeWorkerToken, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	return err
}
