// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"context"
)

type Querier interface {
	AppendLog(ctx context.Context, arg AppendLogParams) error
	CreateRun(ctx context.Context, arg CreateRunParams) error
	GetLogs(ctx context.Context, runID string) ([]GetLogsRow, error)
	GetRun(ctx context.Context, id string) (GetRunRow, error)
	ListRuns(ctx context.Context) ([]ListRunsRow, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
}

var _ Querier = (*Queries)(nil)
