// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"
)

type LogEntry struct {
	ID        int32     `json:"id"`
	RunID     string    `json:"run_id"`
	Timestamp time.Time `json:"timestamp"`
	Stream    string    `json:"stream"`
	Data      string    `json:"data"`
}

type Repo struct {
	CloneUrl string `json:"clone_url"`
}

type Run struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt32  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	GitLink       string         `json:"git_link"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
	RepoUrl       sql.NullString `json:"repo_url"`
}

type SarifFinding struct {
	ID          int32          `json:"id"`
	RunID       string         `json:"run_id"`
	RuleRef     string         `json:"rule_ref"`
	Message     string         `json:"message"`
	Path        string         `json:"path"`
	Line        sql.NullInt32  `json:"line"`
	Fingerprint sql.NullString `json:"fingerprint"`
}

type SarifRule struct {
	ID        string       `json:"id"`
	RuleID    string       `json:"rule_id"`
	Tool      string       `json:"tool"`
	Severity  string       `json:"severity"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type WorkerToken struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
