// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"database/sql"
	"time"
)

type LogEntry struct {
	ID        int32     `json:"id"`
	RunID     string    `json:"run_id"`
	Timestamp time.Time `json:"timestamp"`
	Stream    string    `json:"stream"`
	Data      string    `json:"data"`
}

type Run struct {
	ID         string        `json:"id"`
	Status     string        `json:"status"`
	StartedAt  time.Time     `json:"started_at"`
	FinishedAt sql.NullTime  `json:"finished_at"`
	ExitCode   sql.NullInt32 `json:"exit_code"`
	UiToken    string        `json:"ui_token"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
	GitLink    string        `json:"git_link"`
}
