// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"
)

type LogEntry struct {
	ID        int32     `json:"id"`
	RunID     string    `json:"run_id"`
	Timestamp time.Time `json:"timestamp"`
	Stream    string    `json:"stream"`
	Data      string    `json:"data"`
}

type Repo struct {
	CloneUrl string `json:"clone_url"`
}

type Run struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	StartedAt     time.Time      `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	ExitCode      sql.NullInt32  `json:"exit_code"`
	UiToken       string         `json:"ui_token"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	GitLink       string         `json:"git_link"`
	CommitMessage string         `json:"commit_message"`
	Author        string         `json:"author"`
	Branch        string         `json:"branch"`
	RepoUrl       sql.NullString `json:"repo_url"`
}

type SarifIssue struct {
	ID         int32          `json:"id"`
	SarifRunID string         `json:"sarif_run_id"`
	RuleID     string         `json:"rule_id"`
	Message    string         `json:"message"`
	Path       string         `json:"path"`
	Line       sql.NullInt32  `json:"line"`
	Severity   sql.NullString `json:"severity"`
}

type SarifRun struct {
	ID        string       `json:"id"`
	RunID     string       `json:"run_id"`
	Tool      string       `json:"tool"`
	CreatedAt sql.NullTime `json:"created_at"`
}
