// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
	"database/sql"
)

type Querier interface {
	AppendLog(ctx context.Context, arg AppendLogParams) error
	CheckRepoExists(ctx context.Context, cloneUrl string) (int32, error)
	CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) error
	CreateRepo(ctx context.Context, cloneUrl string) error
	CreateRun(ctx context.Context, arg CreateRunParams) error
	CreateSarifRun(ctx context.Context, arg CreateSarifRunParams) error
	GetLogs(ctx context.Context, runID string) ([]GetLogsRow, error)
	GetRepo(ctx context.Context, cloneUrl string) (string, error)
	GetRun(ctx context.Context, id string) (GetRunRow, error)
	GetRunsWithoutRepoURL(ctx context.Context, limit int32) ([]GetRunsWithoutRepoURLRow, error)
	GetStuckRuns(ctx context.Context, arg GetStuckRunsParams) ([]GetStuckRunsRow, error)
	ListRepos(ctx context.Context) ([]sql.NullString, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error)
	ListSarifIssuesForRepo(ctx context.Context, arg ListSarifIssuesForRepoParams) ([]ListSarifIssuesForRepoRow, error)
	ListSarifIssuesForRun(ctx context.Context, runID string) ([]ListSarifIssuesForRunRow, error)
	UpdateRunRepoURL(ctx context.Context, arg UpdateRunRepoURLParams) error
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
}

var _ Querier = (*Queries)(nil)
